name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'helm/**'
      - 'k8s/**'

concurrency:
  group: app_helm_gitops-main
  cancel-in-progress: true

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go 1.22
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.5

      - name: Build
        run: go build -o go-web-app

      - name: Run tests
        run: go test -v ./...

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Run static analysis
        run: golangci-lint run ./...

  build-and-push:
    runs-on: ubuntu-latest
    needs: [build, code-quality]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/go-gitops-webapp:${{ github.run_id }}
            ${{ secrets.DOCKER_USERNAME }}/go-gitops-webapp:latest

  update-helm-chart:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update Helm chart values
        run: |
          sed -i "s/tag: .*/tag: \"${{ github.run_id }}\"/" k8s/helm/go-gitops-webapp-chart/values.yaml

      - name: Check updated values.yaml
        run: cat k8s/helm/go-gitops-webapp-chart/values.yaml

      - name: Commit and push change
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.NAME }}"
          git add k8s/helm/go-gitops-webapp-chart/values.yaml
          git commit -m "Update Helm chart tag"
          git push
